---
# YAML documents begin with the document separator ---
- hosts: staging
  become: true
  vars:
        container_name: "webapp1"
        app_port: 8082
        target_dir: "{%- if ansible_distribution == 'CentOS' -%}/usr/share/nginx/html{%- elif ansible_distribution == 'Ubuntu' -%}/var/www/html{%- endif %}"
  vars_files:
          - files/cred.vault
  pre_tasks:
  - name: Install EPEL repo
    package: name={{ item }} state=present
    when: ansible_distribution == "CentOS"

  - name: Install Python 3 and pip3
    package:
       name: "{{ item }}"
       state: present
    loop:
          - python3
          - python3-pip

  - name: Install Docker module for Python
    pip:
        name: docker
        executable: pip3

  roles:
    # Le rôle Nginx doit être exécuté en premier
    - role: nginx
    
    # Démarrer la deuxième instance de webapp
    - role: webapp
